service: croupier
frameworkVersion: "3"

# plugin order matters
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_PROJECT_TABLE: ${self:service}-projectTable-${sls:stage}
    PROCESS_IMAGES_FUNCTION_NAME: ${self:service}-${sls:stage}-processImages
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:Query"
            - "dynamodb:UpdateItem"
            - "dynamodb:BatchWriteItem"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-projectTable-${sls:stage}
        - Effect: "Allow"
          Action:
            - "dynamodb:Query"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-projectTable-${sls:stage}/index/*
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource:
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/${self:service}-google-service-account-key
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/${self:service}-groupme-access-token
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:service}-${sls:stage}-processImages
  httpApi:
    authorizers:
      serviceAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl:
          Fn::Join:
          - ''
          - - 'https://cognito-idp.'
            - '${aws:region}'
            - '.amazonaws.com/'
            - Ref: serviceUserPool
        audience:
          - Ref: serviceUserPoolClient

functions:
  getOneProject:
    handler: src/projects.getOne
    events:
      - httpApi:
          path: /projects/{groupId}
          method: get
          authorizer:
            name: serviceAuthorizer
  getProjects:
    handler: src/projects.getMine
    events:
      - httpApi:
          path: /projects
          method: get
          authorizer:
            name: serviceAuthorizer
  createProject:
    handler: src/projects.create
    events:
      - httpApi:
          path: /projects
          method: post
          authorizer:
            name: serviceAuthorizer
  updateOneProject:
    handler: src/projects.updateOne
    events:
      - httpApi:
          path: /projects/{groupId}
          method: put
          authorizer:
            name: serviceAuthorizer
  deleteOneProject:
    handler: src/projects.deleteOne
    timeout: 29
    events:
      - httpApi:
          path: /projects/{groupId}
          method: delete
          authorizer:
            name: serviceAuthorizer
  receiveMessage:
    handler: src/message.receiveMessage
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
    events:
      - httpApi:
          path: /message
          method: post
  processImages:
    handler: src/images.process
    timeout: 300
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
  processImagesHTTP:
    handler: src/images.processHTTP
    timeout: 29
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
    events:
      - httpApi:
          path: /projects/{groupId}/process
          method: post
          authorizer:
            name: serviceAuthorizer
  checkProcess:
    handler: src/images.checkProcess
    timeout: 29
    layers:
      - arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2
    events:
      - httpApi:
          path: /projects/{groupId}/process
          method: get
          authorizer:
            name: serviceAuthorizer

resources:
  Resources:
    ProjectTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: groupId
            AttributeType: S
          - AttributeName: fileId
            AttributeType: S
          - AttributeName: subject
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        KeySchema:
          - AttributeName: groupId
            KeyType: HASH
          - AttributeName: fileId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: subjectIndex
            KeySchema:
              - AttributeName: subject
                KeyType: HASH
              - AttributeName: groupId
                KeyType: RANGE
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - folderId
                - botId
                - replacements
                - emojis
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        TableName: ${self:service}-projectTable-${sls:stage}
    serviceUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: croupier-user-pool-${sls:stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    serviceUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: croupier-user-pool-client-${sls:stage}
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: serviceUserPool
        CallbackURLs: 
          - http://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders: 
          - COGNITO
    serviceUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain 
      Properties:
        UserPoolId: 
          Ref: serviceUserPool
        Domain: croupier-user-pool-domain-${sls:stage}
