name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: deploy dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
      with:
        node-version: 22.x
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@f5f0c17d6ef97718c03f2c0a87c5d9b0bacbb1d8
      with:
        args: deploy --stage dev
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
